### ISSUE TITLE
Test the packaged chrome app (link inside) with chromium

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#12]
https://chrome.google.com/webstore/detail/iguana/obcmnddljhphjndfadmkfipjpjoebmlp

"​19:47 eyedea @jl777:  can I suppose that chrome and chromium are same for our task?
​
19:53 jl777 no
​
19:54 chromium has different defaults, different internals, not sure it will work at all. maybe there is a way to do so, but it has not been verified and there was a case where using chromium didnt work, but chrome did
​
19:54 maybe it is just the debug mode that has issues"

**Comment by flamingice** [comment]
I installed the app on chromium and it was loading fine. I could click around but did not test actual functions. 
![Screenshot](http://storage5.static.itmages.com/i/15/1220/h_1450594203_2614304_6f50bc7856.png)

**Comment by msg4vivek** [comment]
T350 in phab

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T350
