### ISSUE TITLE
creating matched pairs of API request/response/template

### ISSUE THREAD

**Issue by msg4vivek** [SuperNETorg/iguana_dev#17]
The template is needed to define which return fields are required. Depending on the template type supported, we will probably need some wildcard matching, range matching, etc

**Comment by stacksavings** [comment]
My dev looked at this, he had this question..

 form will be there with some fields like email id, password, mobile number... When the user enter the credentials then the system should check if the credentials are in the correct format. For e.g. If a user entered email id in wrong format then one warning should display before posting the data. 
Is it like that..?

**Comment by msg4vivek** [comment]
T351 in phab

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T352.
