### ISSUE TITLE
Bug with graphics on coin management screen

### ISSUE THREAD

**Issue by msg4vivek** [SuperNETorg/iguana_dev#18]
Some details - 

.....there is no debug console for installed apps. You can just open the console when you are in the development framework....it seems we need to make it perfect during the iguana_dev if the chrome debug console doesnt work for packaged apps
​......i think the icon is not of iguana, but of gecko

**Comment by ablaze8** [comment]
I am not sure if I am following you @msg4vivek. Would you please provide a screen snippet to pin point your concern. I appreciate your help.

**Comment by msg4vivek** [comment]
it is related to the icon which seems to be of gecko as mentioned by jl777

**Comment by jl777** [comment]
it appears on the chrome store link, i think the iguana_dev just needs to make this a "skinnable" thing so that iguana_stable can put whatever image deemed best when building the packaged app


https://chrome.google.com/webstore/detail/iguana/obcmnddljhphjndfadmkfipjpjoebmlp

the above URL shows the gecko icon in slack

**Comment by jl777** [comment]
this sort of thing belongs in the iguana_stable repo as it has nothing to do with functionality

**Comment by ablaze8** [comment]
Thanks for your constructive comments, @jl777 and @msg4vivek, I appreciate it ! One question thought is do the team have an idea in mind as to what icon needs to be used or has any brainstorming been done on that ?

I agree it looks like a gecko, but I used use a linux distribution called SuSE / openSuSE Linux from Novell, which also seem be using a similar icon to iguana ( or iguana not sure ) and it's their mascot as well.

So all that I am saying is we have be sure about authentic and royalty free icon.

**Comment by msg4vivek** [comment]
Will move to iguana_stable
