### ISSUE TITLE
passphrases and accounts management

### ISSUE THREAD

**Issue by jl777** [SuperNETorg/iguana_dev#19]
Each agent will have its own .conf file and there will also be a main SuperNET.conf file
in this file the password is in the "secret" field. to keep it secure a layer of encryption will be added so that the NXT ui style login process can be used.

On startup, it wont have any passphrase, so would only be able to do publicly accessible things

once a 12 word passphrase (or hex string) is input, it will decode into an account and a matching .conf file(s) will be created. changes made to this .conf file(s) will only be decodable during sessions that have input the high entropy passphrase. this passphrase is active during the session, but will need to be reinput after a refresh

For example, the instantdex exchange apikeys can be input in a page after login and such apikeys would only be accessible to one who can login

**Comment by msg4vivek** [comment]
T353

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T353
