### ISSUE TITLE
Peer management tab - create basic version

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#2]
eyedea is working on it.

**Comment by msg4vivek** [comment]
hi there, just a small query - are below part of this issue - 

4:04 AM <eyedea> There is task list:
4:04 AM <eyedea> -List of peers
4:04 AM <eyedea> -Button to disconnect peer
4:04 AM <eyedea> -Search field
4:04 AM <eyedea> -Sortable column

just wanted to make sure that these tasks are covered somewhere for development. 

Thanks a lot...

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T346
