### ISSUE TITLE
Bugs with #24 ( Details inside )

### ISSUE THREAD

**Issue by ablaze8** [SuperNETorg/iguana_dev#25]
For details,.please click here ==> https://github.com/SuperNETorg/iguana_dev/pull/24  <==

**Comment by black-owling** [comment]
Fixed missing images issue. 
Fixed local storage, now using chrome storage.
Refactored peerlist.js a bit.

**Comment by ablaze8** [comment]
Closing the issue, I recreated this tab in the https://github.com/SuperNETorg/iguana_dev/tree/peers-tab-fix branch, still need to add sorting and filtering though.

**Comment by ablaze8** [comment]
Closing the issue, I recreated this tab in the https://github.com/SuperNETorg/iguana_dev/tree/peers-tab-fix branch, still need to add sorting and filtering though.
