### ISSUE TITLE
Create HTML/JS snippet that interacts with a .pexe (echo test)

### ISSUE THREAD

**Issue by rolfedh** [SuperNETorg/iguana_dev#28]
https://sprnt.slack.com/archives/iguana/p1450387456000698
The #iguana conversation that generated this request:

jl777 [4:24 PM] 
@rolfedh: while we are documenting things, can we also workup a set of HTML widgets that can be easily put into any web page? I think all we need to do is make a streamlined JS file and the HTML snippet can load from a directory. so it should be a matter of copy pasting html wherever the widget is wanted, along with a line in the header of the html

​[4:25] 
this would be more for the miniguana and not the full node functionality, but we can get a working widget (not sure if that is the right term) all verified now. maybe google has some sample code for such things?

rolfedh [4:50 PM] 
@jl777: Sure. Let's get clear on the requirements. What do you want the widget to do?

jl777 [4:50 PM] 
exactly the question I wanted to ask you

jahl [4:50 PM] 
lol

rolfedh [4:50 PM] 
:simple_smile:

jl777 [4:51 PM] 
for now it should just do an echo test to make sure the process of widget on random HTML page <-> pexe is working

​[4:51] 
once that works, it is a matter to define what the widget does, make HTML for that widget, change the echo request to something real. right?

rolfedh [4:52 PM] 
Do you want it to live in iguana_dev\js?

jl777 [4:52 PM] 
i dont really care where it is, just want it so anybody can cut and paste html snippet and it works

​[4:52] 
it should be served locally of course

​[4:53] 
so not any hosted thing

​[4:53] 
this way any website is a potential iguana node

​[4:54] 
also a research task to see if there are any web advertising inventory that exists that allows to use the chrome app (in widget form)

​[4:54] 
probably not

​[4:54] 
but doesnt hurt to look for it

rolfedh [4:54 PM] 
Sure.

jl777 [4:55 PM] 
maybe the advertisement could be in the html of the widget which clicks through to a hosted site that runs the chrome app

jahl [4:56 PM] 
if I may interrupt with a noob question.. what is an echo request? is it something along the lines of you send a request of something to (in this case from html to the pexe), and the pexe returns what was asked, so you know the request went to the pexe exactly as requested from the tml?

jl777 [4:56 PM] 
yes

​[4:56] 
like a ping

jahl [4:56 PM] 
thanks :simple_smile:"

**Comment by stacksavings** [comment]
Can we start on this? I'm not sure of exact process and who to contact about hours etc

**Comment by rolfedh** [comment]
Just go for it. Take the initiative.

**Comment by stacksavings** [comment]
I'm asking more from a business perspective, I can have my dev start on
this but who do we check in with for payments, etc?

**Comment by rolfedh** [comment]
Not sure. Check with James.

**Comment by flamingice** [comment]
(Question of @stacksavings has been answered on Slack so I removed the comments)

**Comment by black-owling** [comment]
I can assign this task to myself, but I have some questions.
Should widget be able to be injected to any page on internet? How it would be organised at all?
If we can tell developer of parent html, that he should create empty div with id "iguana_widget_container" or something like this, then this would be handled. Widget will be in place, where site owner wants it to be.

**Comment by ablaze8** [comment]
I would suggest this to make it look like a dashboard on the home page. Where it says "iguana is fast."

**Comment by black-owling** [comment]
copypasting this from slack.
Not all sites on Internet have free space at right margin. Idea is (if I got it right) to be able to inject HTML snippet into www.generic-website.com. And if this generic-website doesn't have free space - it would at least look ugly. One workaround is small absolutely positioned button, that will grow into full functional modal window on click and shrink after task is performed.

**Comment by jl777** [comment]
I was thinking something that can be configured as to dimension and maybe it is just a smart button, like "pay with BTC" and an amount entry form.

so something that is cut and pasted into any random html page as it needs to be something not-really devs will have to be able to do

**Comment by ablaze8** [comment]
Oh I see now we want to embed iguana widget on any website, and not the widget inside iguana app.

@jl777 : So want to iguana any random webpage, regardless the web bowser?

**Comment by black-owling** [comment]
Here is example jl777 gave me:
https://developers.coinbase.com/docs/merchants/payment-buttons
So, what we need is a sample of html code, that any website owner can use in his page, right?
I suggest to ask hypothetical user to create a div with id "iguana_widget" or something like this and link custom script to his page.
This script will check for this div and create html markdown depending on div's dimensions.
For example - if div's width 160 and height is 60 px, then script will generate small input field and button, if 160x260, then there will be few more functons available (and iguana logo ofc). What do you think about it?

**Comment by vineetbhargav86** [comment]
@jl777 @flamingice @ablaze8 I am assigning this to myself. However, i would like to confirm my understanding before starting on this.

I will be splitting this work as follows - 
1. HTML code containing a div element with specific id and a script tag : This will convert div into a button which when clicked on, will open a dialog box with an iframe
2. A html page containing a simple form. This is what generated iframe will be rendering.

This solution will also cater to automatically adjusting to div size in case we want to show the target form in a page rather than in a dialog box.

Let me know if you are fine with it and i will start working on it.

**Comment by msg4vivek** [comment]
more details from james about the task - 

--> 
as long as we can show webmasters some HTML snippet they can put into their page and it properly issues iguana API, that is the key. I cannot speak to the details of the HTML as I am not expert in it
​
there are many places that offer some html code for webmasters to put into their websites
​
thermometers, stock prices, etc.
​
just want the same sort of thing, that is able to issue iguana postCall into the pexe
​
we would need to make sure the webmaster knows to copy the iguana JS dir to their website

**Comment by msg4vivek** [comment]
T356 in phabricator

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T356
