### ISSUE TITLE
Create Blockexplorer tab

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#4]

**Comment by javlc** [comment]
I wish to take this task. 
Assigning to myself. FYI

**Comment by javlc** [comment]
Nevermind, just saw the related phabricator task, which is already assigned.
https://phabricator.supernet.org/T306.
I am removing myself from assignment. Apologies and thanks.

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T343
