### ISSUE TITLE
Create coin management tab

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#5]

**Comment by ablaze8** [comment]
Do we have a wire frame or mock diagram about how should it look like ?

**Comment by black-owling** [comment]
Nope. For now it should be useful for testing API.
Create your own mock (or look for it at similar programs) and ask for feedback in slack.

**Comment by msg4vivek** [comment]
Duplicate of T302 in phab.

**Comment by flamingice** [comment]
Moved to https://phabricator.supernet.org/T302
