### ISSUE TITLE
Port existing SN Lite GUI to iguana

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#6]

**Comment by jl777** [comment]
i think the current GUI should just work as chrome app, but we need to get this into the same codebase.

for now it can be a totally separate "tab", maybe it is just started with a button from the basic iguana app. once that is working we can go to the next step

**Comment by ablaze8** [comment]
@jl777 : "for now it can be a totally separate "tab" ... 

did you mean that it should run as chrome extension and not as a web application ? Or are you referring to the fact that it launches in a new window ?

**Comment by jl777** [comment]
I call the different tabs that the current GUI has "tab"
"Debug" "Wallet" "iguana", etc

**Comment by flamingice** [comment]
(Current SN Lite at https://github.com/Tosch110/SuperNet-Lite)

**Comment by msg4vivek** [comment]
Task T349 in phabricator

**Comment by flamingice** [comment]
moved to https://phabricator.supernet.org/T310
